
package com.sample.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ReporterInterface", targetNamespace = "http://com.sample/port")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReporterInterface {


    /**
     * 
     * @param client
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetReport")
    @WebResult(targetNamespace = "http://com.sample/types")
    @RequestWrapper(localName = "GetReport", targetNamespace = "http://com.sample/types", className = "com.sample.service.GetReportType")
    @ResponseWrapper(localName = "GetReportResponse", targetNamespace = "http://com.sample/types", className = "com.sample.service.GetReportResponseType")
    public String getReport(
        @WebParam(name = "client", targetNamespace = "http://com.sample/types")
        ClientType client);

}
